import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "kingoma hotel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className="w-full h-[85px] z-1 flex justify-between items-center pl-8 pr-8 absolute top-0 left-0 bottom-0 right-0 bg-inherit" >
          <article className="w-[4.7%] h-[63%] bg-[transparent] ">
            <img src={"./logo.png"} className="w-full h-[100%]" />
          </article>

          <ul className="flex w-[37%] bg-slate-20 justify-between z-9999 text-[black]">
            <Link href={"/"}>
              <li className=" z-9 cursor-pointer text-[14px] font-medium">Home</li>
            </Link>

            <Link href={"./room"}>
              <li className=" z-9 cursor-pointer text-[14px] font-medium">Room</li>
            </Link>

            <Link href={"./facilities"}>
              <li className=" z-9 cursor-pointer text-[14px] font-medium"> Facilities</li>
            </Link>

            <Link href={"./about"}>
              <li className=" z-9 cursor-pointer text-[14px] font-medium">About Us</li>
            </Link>

          </ul>

          <article className="w-[12%] h-[33%] bg-[#FE7401] z-9 text-[white] cursor-pointer text-[14px] font-medium flex justify-around items-center pl-4 pr-4">
            <img src="./Calendar.png" width={"18px"} height={"18px"} />
            <p className="text-[12px] font-medium">Reservation</p>
          </article>
        </div>

        {children}

        <section className="w-full h-[38vh] bg-[#d5d3d] mt-[2rem] flex flex-col justify-between pl-10 pr-10 items-center">
          <h1 className="font-mono text-[30px] font-bold">Feel free to say hello</h1>

          <div className="w-full h-[90%] bg-[#bdb9c] flex justify-between items-center mt-5">
            <article className="w-[45%] h-[80%] bg-[#7fa1a] flex justify-between">
              <div className="w-[23%] h-[30%] bg-[#d0d68] rounded-full">
                <img src={"./logo.png"} className="w-full h-[100%]" />

              </div>

              <p className="text-[10px] w-40%] pr-5 pl-5 ">Perched on the edge of the Wikki Hills, Kigamo commands breathtaking views down the valley that borders the Yankari Game Reserve. Enjoy exclusive game viewing, thrilling night game drives, bush dining, amazing Nigerian culture and old-fashioned safari luxury.
              </p>
            </article>

            <article className="w-[50%] h-[80%] bg-[#e8d3b] flex gap-5">
              <div className="w-[20%] h-[100%] bg-[#3daab] text-[10px]">
                <h1 className="text-[13px] font-medium">Address</h1>
                <p className="pt-2">Wikki Camp, Yankari Reserve, Bauchi</p>

                <h1 className="text-[13px] pt-4 font-medium">Phone</h1>
                <p className="pt-2">+234 803 102 4720</p>
              </div>

              <div className="w-[20%] h-[100%] bg-[#3daab] text-[10px]">
                <h1 className="text-[13px] font-medium">Email</h1>
                <p className="pt-2">hello@kigamo.com</p>
              </div>

              <div className="w-[20%] h-[100%] bg-[#3daab] text-[10px] ml-4">
                <h1 className="text-[13px] font-medium">ABOUT</h1>
                <p className="pt-2">About</p>
                <p className="pt-2">Accessibility</p>
                <p className="pt-2">Awards</p>
              </div>

              <div className="w-[20%] h-[100%] bg-[#3daab] text-[10px]">
                <p className="pt-7">Policies</p>
                <p className="pt-2">Development</p>
                <p className="pt-2">Careers</p>
              </div>

              <div className="w-[20%] h-[100%] bg-[#3daab] text-[10px]">
                <p className="pt-7">News & Press</p>
                <p className="pt-2">Videos</p>
                <p className="pt-2">Covid-19</p>
              </div>

            </article>
          </div>

        </section>
      </body>
    </html>
  );
}
